pawn(Board, Row, Col, Type) :-
nth0(Row, Board, List),
nth0(Col, List, Type).

board(Board) :- Board =
[
[e, e, e, e, e, e, e, e],
[e, e, e, e, e, e, e, e],
[e, e, e, e, e, e, e, e],
[e, e, e, w, b, e, e, e],
[e, e, e, b, w, e, e, e],
[e, e, e, e, e, e, e, e],
[e, e, e, e, e, e, e, e],
[e, e, e, e, e, e, e, e]
].

display_board :- board(Board),
  pawn(Board,0,0, P00),
  pawn(Board,0,1, P01),
  pawn(Board,0,2, P02),
  pawn(Board,0,3, P03),
  pawn(Board,0,4, P04),
  pawn(Board,0,5, P05),
  pawn(Board,0,6, P06),
  pawn(Board,0,7, P07),
  pawn(Board,1,0, P10),
  pawn(Board,1,1, P11),
  pawn(Board,1,2, P12),
  pawn(Board,1,3, P13),
  pawn(Board,1,4, P14),
  pawn(Board,1,5, P15),
  pawn(Board,1,6, P16),
  pawn(Board,1,7, P17),
  pawn(Board,2,0, P20),
  pawn(Board,2,1, P21),
  pawn(Board,2,2, P22),
  pawn(Board,2,3, P23),
  pawn(Board,2,4, P24),
  pawn(Board,2,5, P25),
  pawn(Board,2,6, P26),
  pawn(Board,2,7, P27),
  pawn(Board,3,0, P30),
  pawn(Board,3,1, P31),
  pawn(Board,3,2, P32),
  pawn(Board,3,3, P33),
  pawn(Board,3,4, P34),
  pawn(Board,3,5, P35),
  pawn(Board,3,6, P36),
  pawn(Board,3,7, P37),
  pawn(Board,4,0, P40),
  pawn(Board,4,1, P41),
  pawn(Board,4,2, P42),
  pawn(Board,4,3, P43),
  pawn(Board,4,4, P44),
  pawn(Board,4,5, P45),
  pawn(Board,4,6, P46),
  pawn(Board,4,7, P47),
  pawn(Board,5,0, P50),
  pawn(Board,5,1, P51),
  pawn(Board,5,2, P52),
  pawn(Board,5,3, P53),
  pawn(Board,5,4, P54),
  pawn(Board,5,5, P55),
  pawn(Board,5,6, P56),
  pawn(Board,5,7, P57),
  pawn(Board,6,0, P60),
  pawn(Board,6,1, P61),
  pawn(Board,6,2, P62),
  pawn(Board,6,3, P63),
  pawn(Board,6,4, P64),
  pawn(Board,6,5, P65),
  pawn(Board,6,6, P66),
  pawn(Board,6,7, P67),
  pawn(Board,7,0, P70),
  pawn(Board,7,1, P71),
  pawn(Board,7,2, P72),
  pawn(Board,7,3, P73),
  pawn(Board,7,4, P74),
  pawn(Board,7,5, P75),
  pawn(Board,7,6, P76),
  pawn(Board,7,7, P77),
  writeln(''),
  writeln('-----------------'),
  write('|'),
  write(P00),
  write('|'),
  write(P01),
  write('|'),
  write(P02),
  write('|'),
  write(P03),
  write('|'),
  write(P04),
  write('|'),
  write(P05),
  write('|'),
  write(P06),
  write('|'),
  write(P07),
  write('|'), 
  writeln(''),
  writeln('-----------------'),
  write('|'),
  write(P10),
  write('|'),
  write(P11),
  write('|'),
  write(P12),
  write('|'),
  write(P13),
  write('|'),
  write(P14),
  write('|'),
  write(P15),
  write('|'),
  write(P16),
  write('|'),
  write(P17),
  write('|'),
  writeln(''),
  writeln('-----------------'),
  write('|'),
  write(P20),
  write('|'),
  write(P21),
  write('|'),
  write(P22),
  write('|'),
  write(P23),
  write('|'),
  write(P24),
  write('|'),
  write(P25),
  write('|'),
  write(P26),
  write('|'),
  write(P27),
  write('|'),
  writeln(''),
  writeln('-----------------'),
  write('|'),
  write(P30),
  write('|'),
  write(P31),
  write('|'),
  write(P32),
  write('|'),
  write(P33),
  write('|'),
  write(P34),
  write('|'),
  write(P35),
  write('|'),
  write(P36),
  write('|'),
  write(P37),
  write('|'),
  writeln(''),
  writeln('-----------------'),
  write('|'),
  write(P40),
  write('|'),
  write(P41),
  write('|'),
  write(P42),
  write('|'),
  write(P43),
  write('|'),
  write(P44),
  write('|'),
  write(P45),
  write('|'),
  write(P46),
  write('|'),
  write(P47),
  write('|'),
  writeln(''),
  writeln('-----------------'),
  write('|'),
  write(P50),
  write('|'),
  write(P51),
  write('|'),
  write(P52),
  write('|'),
  write(P53),
  write('|'),
  write(P54),
  write('|'),
  write(P55),
  write('|'),
  write(P56),
  write('|'),
  write(P57),
  write('|'), 
  writeln(''),
  writeln('-----------------'),
  write('|'),
  write(P60),
  write('|'),
  write(P61),
  write('|'),
  write(P62),
  write('|'),
  write(P63),
  write('|'),
  write(P64),
  write('|'),
  write(P65),
  write('|'),
  write(P66),
  write('|'),
  write(P67),
  write('|'), 
  writeln(''),
  writeln('-----------------'),
  write('|'),
  write(P70),
  write('|'),
  write(P71),
  write('|'),
  write(P72),
  write('|'),
  write(P73),
  write('|'),
  write(P74),
  write('|'),
  write(P75),
  write('|'),
  write(P76),
  write('|'),
  write(P77),
  writeln('|'),
  writeln('-----------------').
